change Makefile && add revision

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -1,70 +1,85 @@
-UNAME_S := $(shell uname -s)
-
 GCC = gcc
-CFLAGS = -Wall -pipe -g -m64
-CFLAGS += -march=native -mtune=native -O3
-CFLAGS += -DNDEBUG
-#CFLAGS += -pg
-#LDFLAGS += -pg
 
-BINDIR = ./bin_obj
-BIN_OBJ = ./bin_obj
-OUTLIBDIR = ../lib
-OUTINCDIR = ../include/stutils
-SO_OBJ = ./so_obj
+OUTINC_DIR = ../include/
+BIN_DIR=../bin
+OUTLIB_DIR=../lib
 
-UNAME_S := $(shell uname -s)
+OBJ_DIR=./.objs
+DEP_DIR=./.deps
+
+include flags.mk
+include templates.mk
+
+PROJECT = stutils
+CONFIG_INC = st_macro.h
+OUT_CONFIG = $(OUTINC_DIR)/$(PROJECT)/$(CONFIG_INC)
+
+INCS = st_dict.h \
+       st_alphabet.h \
+       st_utils.h \
+       st_conf.h \
+       st_log.h \
+       st_queue.h \
+       st_stack.h \
+       st_heap.h \
+       st_net.h \
+       st_io.h \
+       st_opt.h \
+       st_semaphore.h
+
+OBJS = st_dict.o \
+       st_alphabet.o \
+       st_utils.o \
+       st_conf.o \
+       st_log.o \
+       st_queue.o \
+       st_stack.o \
+       st_heap.o \
+       st_net.o \
+       st_io.o \
+       st_opt.o \
+       st_semaphore.o
+
 ifeq ($(UNAME_S),Darwin)
-LDFLAGS+=
-else
-LDFLAGS+=-lm
-endif
-LDFLAGS += -lpthread
-LDFLAGS += -Wl,-rpath,'$$ORIGIN'
-LDFLAGS += -Wl,-rpath,$(shell pwd)/$(OUTLIBDIR)
-
-INC = st_dict.h st_alphabet.h st_utils.h st_conf.h st_log.h \
-             st_macro.h st_queue.h st_stack.h st_heap.h st_net.h \
-             st_io.h st_opt.h st_semaphore.h
-TARGET_INC = $(addprefix $(OUTINCDIR)/, $(INC))
-
-OBJ_SO = st_dict.o st_alphabet.o st_utils.o st_conf.o st_log.o \
-         st_queue.o st_stack.o st_heap.o st_net.o st_io.o st_opt.o \
-         st_semaphore.o
-
-ifeq ($(UNAME_S),Darwin)
-TARGET_SO = $(OUTLIBDIR)/libstutils.dylib
+TARGET_SO = $(OUTLIB_DIR)/libstutils.dylib
 SO_FLAGS = -dynamiclib -install_name $(shell pwd)/$(TARGET_SO)
 else
-TARGET_SO = $(OUTLIBDIR)/libstutils.so
+TARGET_SO = $(OUTLIB_DIR)/libstutils.so
 SO_FLAGS = -shared
 endif
 
-TEST_BIN = st-utils-test
+TEST_BINS = tests/st-utils-test
 
-TARGET_TEST_BIN = $(addprefix $(BINDIR)/, $(TEST_BIN))
+.PHONY: all config inc clean lint-check
+.PHONY: test val-test
+.PHONY: prepare-doc gen-doc publish-doc
 
-.PHONY: all preparedir clean test doc lint-check
+all: inc $(TARGET_SO)
 
-all:  preparedir $(TARGET_SO) $(TARGET_INC)
+# always check revision
+config:
+	@./replace_revision.sh $(CONFIG_INC) $(OUT_CONFIG)
 
-preparedir: 
-	@mkdir -p $(BIN_OBJ)
-	@mkdir -p $(SO_OBJ)
-	@mkdir -p ${BINDIR}
-	@mkdir -p ${OUTLIBDIR}
-	@mkdir -p ${OUTINCDIR}
+# copy config.h when updated
+$(OUT_CONFIG): $(CONFIG_INC)
+	./replace_revision.sh $(CONFIG_INC) $(OUT_CONFIG) 1
 
-$(SO_OBJ)/%.o : %.c 
+OUT_INCS = $(addprefix $(OUTINC_DIR)/$(PROJECT)/,$(INCS))
+
+inc: $(OUT_INCS) config $(OUT_CONFIG)
+
+$(foreach f,$(INCS),$(eval $(call copy_inc,$f,$(OUTINC_DIR)/$(PROJECT)/$f)))
+
+$(TARGET_SO) : $(addprefix $(OBJ_DIR)/,$(OBJS))
+	@mkdir -p "$(dir $@)"
+	$(GCC) $(CFLAGS) $(LDFLAGS) $(SO_FLAGS) -o $@ $^
+
+$(OBJ_DIR)/%.o : %.c %.h
+	@mkdir -p "$(dir $@)"
 	$(GCC) $(CFLAGS) -fPIC -c -o $@ $<
 
-$(TARGET_INC) : $(INC)
-	cp $^ ${OUTINCDIR}
-
-$(TARGET_SO) : $(addprefix $(SO_OBJ)/, $(OBJ_SO))
-	$(GCC) $(CFLAGS) $(SO_FLAGS) -o $@ $^
-
-$(BIN_OBJ)/%.o : %.c
+$(BIN_DIR)/%.o : %.c %.h
+	@mkdir -p "$(dir $@)"
 	$(GCC) $(CFLAGS) -c -o $@ $^ 
 
 
@@ -72,20 +87,62 @@ lint-check : *.h *.cpp *.c
 	splint +posixlib +D__gnuc_va_list=int -fileextensions $^ 
 
 clean:
-	rm -rf ${BIN_OBJ}
-	rm -rf ${BINDIR}
-	rm -rf ${SO_OBJ}
-	rm -rf ${OUTLIBDIR}
-	rm -rf ${OUTINCDIR}
-	rm -rf ../include
+	rm -rf ${OBJ_DIR}
+	rm -rf ${DEP_DIR}
+	rm -rf ${BIN_DIR}
+	rm -rf ${OUTLIB_DIR}
+	rm -rf ${OUTINC_DIR}
 	rm -f tags cscope.*
 
-$(TARGET_TEST_BIN) : $(BINDIR)/%-test: $(addprefix $(BIN_OBJ)/, %-test.o) $(TARGET_SO) $(TARGET_INC)
-	$(GCC) $(CFLAGS) -o $@ $< -L$(OUTLIBDIR) -lstutils $(LDFLAGS) 
+TEST_TARGETS = $(addprefix $(OBJ_DIR)/,$(TEST_BINS))
 
-test: preparedir $(TARGET_TEST_BIN)
-	@result=0; for x in $(TARGET_TEST_BIN); do printf "Running $$x ..."; ./$$x >/dev/null 2>&1; if [ $$? -ne 0 ]; then echo "... FAIL $$x"; result=1; else echo "... SUCCESS";  fi;  done; exit $$result
+test: inc $(TARGET_SO) $(TEST_TARGETS)
+	@result=0; \
+     for x in $(TEST_TARGETS); do \
+       printf "Running $$x ..."; \
+       ./$$x >/dev/null 2>&1; \
+       if [ $$? -ne 0 ]; then \
+         echo "... FAIL $$x"; \
+         result=1; \
+       else \
+         echo "... SUCCESS"; \
+       fi; \
+     done; \
+     exit $$result
 
-gen-doc:
-	doxygen doc/Doxyfile
-	cd html && git add * && git commit -a -m"generate doc on $(shell date)" && git push origin gh-pages
+val-test: inc $(TARGET_SO) $(TEST_TARGETS)
+	@result=0; \
+     for x in $(TEST_TARGETS); do \
+       printf "Valgrinding $$x ..."; \
+       valgrind ./$$x; \
+       if [ $$? -ne 0 ]; then \
+         echo "... FAIL $$x"; \
+         result=1; \
+       else \
+         echo "... SUCCESS"; \
+       fi; \
+     done; \
+     exit $$result
+
+# complie and link tests
+$(OBJ_DIR)/%: %.c
+	@mkdir -p "$(dir $@)"
+	$(GCC) $(CFLAGS) -UNDEBUG -o $@ $< -L$(OUTLIB_DIR) -l$(PROJECT) $(LDFLAGS) 
+
+gen-doc: prepare-doc
+	rm -rf html/*
+	doxygen doc/Doxyfile > /dev/null
+
+prepare-doc:
+	mkdir -p html
+	if [ ! -d html/.git ]; then \
+      git clone git@github.com:wantee/$(PROJECT).git html; \
+    fi
+	cd html && \
+    git checkout gh-pages
+
+publish-doc: gen-doc
+	cd html && \
+	git add * && \
+	git commit -a -m"generate doc on $(shell date)" && \
+	git push origin gh-pages
